[package]
name = "yampd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.0"
lofty = "0.11.0"
rusqlite = "0.28.0"
symphonia = { version = "0.5.2", features = ["all"] }
